version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: conduit-postgres
    environment:
      POSTGRES_DB: conduit_rag
      POSTGRES_USER: conduit
      POSTGRES_PASSWORD: conduit_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./lib/rag/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U conduit -d conduit_rag"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rag-network

  # Optional: Adminer for database management
  adminer:
    image: adminer:latest
    container_name: conduit-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - rag-network

volumes:
  postgres_data:

networks:
  rag-network:
    driver: bridge
